name: Validar codigo Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Ejecutar script de prueba
        run: python precios.py
